# Generated by Django 5.1.6 on 2025-02-13 23:02

import django.db.models.deletion
import finance.const
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='user_details',
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'currency',
                    models.ForeignKey(
                        default=finance.const.CurrencyEnum['USD'],
                        on_delete=django.db.models.deletion.PROTECT,
                        to='finance.currency',
                    ),
                ),
            ],
        ),
    ]
